[package]
name = "hotline"
version = "0.1.0"
edition = "2018"

[dependencies.imgui-sys]
version = "0.8.0"

[dependencies]
bitmask = "^0.5.0"

[dependencies.windows]
version = "0.27"
features = [
    "alloc",
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Graphics_Gdi",
    "Win32_Graphics_Direct3D_Fxc",
    "Win32_Graphics_Direct3D12",
    "Win32_Graphics_Dxgi_Common",
    "Win32_System_LibraryLoader",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_System_Threading",
    "Win32_System_WindowsProgramming",
]

[[bin]]
name = "hello_world"
path = "samples/hello_world/main.rs"