[package]
name = "d3d12"
version = "0.1.0"
edition = "2018"

[lib]
name = "d3d12"
path = "d3d12.rs"

[dependencies]
gfx = { path = "..", package = "gfx" }

[dependencies.windows]
version = "0.27"
features = [
    "alloc",
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_Graphics_Direct3D_Fxc",
    "Win32_Graphics_Direct3D12",
    "Win32_Graphics_Dxgi_Common",
    "Win32_System_LibraryLoader",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_Threading",
    "Win32_System_WindowsProgramming",
]